// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const key = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY"
  ]);
  if (!key) {
    throw new Error("SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY) is required");
  }
  return key;
}
function supabaseForUser(ctx) {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in to this app first." }],
    isError: true
  };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the profile of the signed-in Bharath Builders user (name, username, phone, status).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, full_name, username, phone_number, user_status").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult({ email: ctx.getUserEmail() ?? null, profile: data ?? null });
  }
});

// src/lib/mcp/tools/list-sites.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^4.4.3";
var list_sites_default = defineTool2({
  name: "list_sites",
  title: "List sites",
  description: "List project sites with status, code, dates and base address. Optionally search by name and include inactive sites.",
  inputSchema: {
    search: z.string().trim().optional().describe("Case-insensitive match on site name or code."),
    include_inactive: z.boolean().optional().describe("Include inactive sites. Defaults to false."),
    limit: z.number().int().optional().describe("Max rows to return (1-100, default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, include_inactive, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("project_sites").select("id, site_name, site_code, status, flag, start_date, end_date, base_address, is_active").is("deleted_at", null).order("site_name").limit(take);
    if (!include_inactive) query = query.eq("is_active", true);
    if (search) query = query.or(`site_name.ilike.%${search}%,site_code.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, sites: data ?? [] });
  }
});

// src/lib/mcp/tools/list-activities.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_activities_default = defineTool3({
  name: "list_activities",
  title: "List field activities",
  description: "List field activities (site visits, tasks, GRN events) with date, type, site, status and check-in details.",
  inputSchema: {
    from_date: z2.string().trim().optional().describe("Earliest activity date, YYYY-MM-DD."),
    to_date: z2.string().trim().optional().describe("Latest activity date, YYYY-MM-DD."),
    site_id: z2.string().trim().optional().describe("Filter to one site id."),
    mine_only: z2.boolean().optional().describe("Only activities created by me. Defaults to false."),
    limit: z2.number().int().optional().describe("Max rows to return (1-100, default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, site_id, mine_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("activity_events").select(
      "id, activity_code, activity_name, activity_type, activity_date, status, site_id, project_id, location_address, check_in_at, check_out_at, remarks"
    ).order("activity_date", { ascending: false }).limit(take);
    if (from_date) query = query.gte("activity_date", from_date);
    if (to_date) query = query.lte("activity_date", to_date);
    if (site_id) query = query.eq("site_id", site_id);
    if (mine_only) query = query.eq("created_by", ctx.getUserId());
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, activities: data ?? [] });
  }
});

// src/lib/mcp/tools/my-attendance.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z3 } from "npm:zod@^4.4.3";
var my_attendance_default = defineTool4({
  name: "my_attendance",
  title: "My attendance",
  description: "Return the signed-in user's attendance records (date, status, check-in/out times, hours) for a date range.",
  inputSchema: {
    from_date: z3.string().trim().optional().describe("Start date, YYYY-MM-DD."),
    to_date: z3.string().trim().optional().describe("End date, YYYY-MM-DD."),
    limit: z3.number().int().optional().describe("Max rows to return (1-100, default 31).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const take = Math.min(Math.max(limit ?? 31, 1), 100);
    let query = supabaseForUser(ctx).from("attendance").select("date, status, check_in_time, check_out_time, total_hours, check_in_address, check_out_address, notes").eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(take);
    if (from_date) query = query.gte("date", from_date);
    if (to_date) query = query.lte("date", to_date);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    const totalHours = (data ?? []).reduce((sum, row) => sum + (Number(row.total_hours) || 0), 0);
    return jsonResult({ count: data?.length ?? 0, total_hours: Number(totalHours.toFixed(2)), records: data ?? [] });
  }
});

// src/lib/mcp/tools/list-procurement-orders.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_procurement_orders_default = defineTool5({
  name: "list_procurement_orders",
  title: "List requisitions and purchase orders",
  description: "List procurement requisitions / purchase orders with number, status, site, budget and delivery date.",
  inputSchema: {
    status: z4.string().trim().optional().describe("Exact status, e.g. 'Requisition', 'PO Issued', 'Paid'."),
    search: z4.string().trim().optional().describe("Match on requisition name, requisition number or PO number."),
    source_type: z4.string().trim().optional().describe("'vendor' for vendor purchase or 'transfer' for internal transfer."),
    limit: z4.number().int().optional().describe("Max rows to return (1-100, default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, source_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("procurement_orders").select(
      "id, requisition_number, po_number, requisition_name, status, source_type, order_date, expected_delivery_date, estimated_budget, site_id, bill_to, ship_to, payment_terms"
    ).order("order_date", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    if (source_type) query = query.eq("source_type", source_type);
    if (search) {
      query = query.or(
        `requisition_name.ilike.%${search}%,requisition_number.ilike.%${search}%,po_number.ilike.%${search}%`
      );
    }
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, orders: data ?? [] });
  }
});

// src/lib/mcp/tools/list-vendors.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z5 } from "npm:zod@^4.4.3";
var list_vendors_default = defineTool6({
  name: "list_vendors",
  title: "List vendors",
  description: "List vendors from Master Data with category, status, GST number and address. Optionally search by name.",
  inputSchema: {
    search: z5.string().trim().optional().describe("Case-insensitive match on vendor name."),
    status: z5.string().trim().optional().describe("Filter by vendor status."),
    limit: z5.number().int().optional().describe("Max rows to return (1-100, default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("vendors").select("id, name, category, status, gst_number, address, services").order("name").limit(take);
    if (search) query = query.ilike("name", `%${search}%`);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, vendors: data ?? [] });
  }
});

// src/lib/mcp/tools/my-expenses.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z6 } from "npm:zod@^4.4.3";
var my_expenses_default = defineTool7({
  name: "my_expenses",
  title: "My expenses",
  description: "List the signed-in user's expense claims with amount, category, status and date, plus a total.",
  inputSchema: {
    from_date: z6.string().trim().optional().describe("Earliest expense date, YYYY-MM-DD."),
    to_date: z6.string().trim().optional().describe("Latest expense date, YYYY-MM-DD."),
    status: z6.string().trim().optional().describe("Filter by claim status, e.g. 'pending', 'approved'."),
    limit: z6.number().int().optional().describe("Max rows to return (1-100, default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("additional_expenses").select("id, expense_date, amount, category, custom_category, description, status, rejection_reason").eq("user_id", ctx.getUserId()).order("expense_date", { ascending: false }).limit(take);
    if (from_date) query = query.gte("expense_date", from_date);
    if (to_date) query = query.lte("expense_date", to_date);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    const total = (data ?? []).reduce((sum, row) => sum + (Number(row.amount) || 0), 0);
    return jsonResult({ count: data?.length ?? 0, total_amount: Number(total.toFixed(2)), expenses: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "ukqgdhsvyadjauscqvhl";
var mcp_default = defineMcp({
  name: "bharath-builders",
  title: "Bharath Builders",
  version: "0.1.0",
  instructions: "Read-only tools for the Bharath Builders field-force app. Use `whoami` to identify the signed-in user, `list_sites` for project sites, `list_activities` for field activities and site visits, `my_attendance` for the user's attendance records, `my_expenses` for their expense claims, and `list_procurement_orders` / `list_vendors` for procurement data. All data is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_sites_default,
    list_activities_default,
    my_attendance_default,
    my_expenses_default,
    list_procurement_orders_default,
    list_vendors_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
